import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { equatorialToGalacticCartesian } from '../src/engine/data/star-mapper.ts';
import type { Nebula } from '../src/engine/contract/catalog-types.ts';

const OUT_FILE = 'public/data/nebulae/nebulae.json';

type NebulaSeed = {
  id: string;
  messierId?: string;
  ngcId?: string;
  nameEn: string;
  nameZh: string;
  type: Nebula['type'];
  raH: number;
  raM: number;
  decDeg: number;
  distanceLy: number;
  apparentMagnitude: number | null;
  sizeArcMinMajor: number;
  sizeArcMinMinor: number;
};

const SEEDS: readonly NebulaSeed[] = [
  // 疏散星团
  {
    id: 'm45',
    messierId: 'M45',
    nameEn: 'Pleiades',
    nameZh: '昴星团',
    type: 'cluster-open',
    raH: 3,
    raM: 47,
    decDeg: 24.12,
    distanceLy: 444,
    apparentMagnitude: 1.6,
    sizeArcMinMajor: 110,
    sizeArcMinMinor: 110,
  },
  {
    id: 'hyades',
    nameEn: 'Hyades',
    nameZh: '毕星团',
    type: 'cluster-open',
    raH: 4,
    raM: 26.9,
    decDeg: 15.87,
    distanceLy: 153,
    apparentMagnitude: 0.5,
    sizeArcMinMajor: 330,
    sizeArcMinMinor: 330,
  },
  {
    id: 'm44',
    messierId: 'M44',
    nameEn: 'Beehive Cluster',
    nameZh: '蜂巢星团',
    type: 'cluster-open',
    raH: 8,
    raM: 40.4,
    decDeg: 19.67,
    distanceLy: 610,
    apparentMagnitude: 3.7,
    sizeArcMinMajor: 95,
    sizeArcMinMinor: 95,
  },
  {
    id: 'm41',
    messierId: 'M41',
    nameEn: 'Little Beehive',
    nameZh: '小蜂巢星团',
    type: 'cluster-open',
    raH: 6,
    raM: 46,
    decDeg: -20.75,
    distanceLy: 2300,
    apparentMagnitude: 4.5,
    sizeArcMinMajor: 38,
    sizeArcMinMinor: 38,
  },
  {
    id: 'm35',
    messierId: 'M35',
    nameEn: 'Shoe-Buckle Cluster',
    nameZh: 'M35 疏散星团',
    type: 'cluster-open',
    raH: 6,
    raM: 9,
    decDeg: 24.35,
    distanceLy: 2800,
    apparentMagnitude: 5.3,
    sizeArcMinMajor: 28,
    sizeArcMinMinor: 28,
  },
  {
    id: 'm7',
    messierId: 'M7',
    nameEn: 'Ptolemy Cluster',
    nameZh: '托勒密星团',
    type: 'cluster-open',
    raH: 17,
    raM: 53.9,
    decDeg: -34.82,
    distanceLy: 980,
    apparentMagnitude: 3.3,
    sizeArcMinMajor: 80,
    sizeArcMinMinor: 80,
  },
  {
    id: 'ngc-869',
    ngcId: '869',
    nameEn: 'Double Cluster (h Persei)',
    nameZh: '双星团',
    type: 'cluster-open',
    raH: 2,
    raM: 20,
    decDeg: 57.13,
    distanceLy: 7500,
    apparentMagnitude: 3.7,
    sizeArcMinMajor: 60,
    sizeArcMinMinor: 60,
  },
  // 球状星团
  {
    id: 'm13',
    messierId: 'M13',
    nameEn: 'Great Hercules Cluster',
    nameZh: '武仙座球状星团',
    type: 'cluster-globular',
    raH: 16,
    raM: 41.7,
    decDeg: 36.46,
    distanceLy: 25300,
    apparentMagnitude: 5.8,
    sizeArcMinMajor: 20,
    sizeArcMinMinor: 20,
  },
  {
    id: 'm92',
    messierId: 'M92',
    nameEn: 'Hercules Cluster',
    nameZh: 'M92 球状星团',
    type: 'cluster-globular',
    raH: 17,
    raM: 17.1,
    decDeg: 43.13,
    distanceLy: 26700,
    apparentMagnitude: 6.4,
    sizeArcMinMajor: 14,
    sizeArcMinMinor: 14,
  },
  {
    id: 'm3',
    messierId: 'M3',
    nameEn: 'M3',
    nameZh: 'M3 球状星团',
    type: 'cluster-globular',
    raH: 13,
    raM: 42.2,
    decDeg: 28.38,
    distanceLy: 33900,
    apparentMagnitude: 6.2,
    sizeArcMinMajor: 18,
    sizeArcMinMinor: 18,
  },
  {
    id: 'm22',
    messierId: 'M22',
    nameEn: 'Sagittarius Cluster',
    nameZh: '人马座球状星团',
    type: 'cluster-globular',
    raH: 18,
    raM: 36.4,
    decDeg: -23.9,
    distanceLy: 10600,
    apparentMagnitude: 6.2,
    sizeArcMinMajor: 32,
    sizeArcMinMinor: 32,
  },
  {
    id: 'ngc-5139',
    ngcId: '5139',
    nameEn: 'Omega Centauri',
    nameZh: '半人马座ω',
    type: 'cluster-globular',
    raH: 13,
    raM: 26.8,
    decDeg: -47.48,
    distanceLy: 15800,
    apparentMagnitude: 3.9,
    sizeArcMinMajor: 36,
    sizeArcMinMinor: 36,
  },
  {
    id: 'm5',
    messierId: 'M5',
    nameEn: 'M5',
    nameZh: 'M5 球状星团',
    type: 'cluster-globular',
    raH: 15,
    raM: 18.6,
    decDeg: 2.08,
    distanceLy: 24500,
    apparentMagnitude: 5.6,
    sizeArcMinMajor: 23,
    sizeArcMinMinor: 23,
  },
  // 发射星云
  {
    id: 'm42',
    messierId: 'M42',
    nameEn: 'Orion Nebula',
    nameZh: '猎户座大星云',
    type: 'emission',
    raH: 5,
    raM: 35.3,
    decDeg: -5.38,
    distanceLy: 1344,
    apparentMagnitude: 4.0,
    sizeArcMinMajor: 65,
    sizeArcMinMinor: 60,
  },
  {
    id: 'm8',
    messierId: 'M8',
    nameEn: 'Lagoon Nebula',
    nameZh: '礁湖星云',
    type: 'emission',
    raH: 18,
    raM: 3.8,
    decDeg: -24.38,
    distanceLy: 4100,
    apparentMagnitude: 6.0,
    sizeArcMinMajor: 90,
    sizeArcMinMinor: 40,
  },
  {
    id: 'm20',
    messierId: 'M20',
    nameEn: 'Trifid Nebula',
    nameZh: '三叶星云',
    type: 'emission',
    raH: 18,
    raM: 2.6,
    decDeg: -23.03,
    distanceLy: 5200,
    apparentMagnitude: 6.3,
    sizeArcMinMajor: 28,
    sizeArcMinMinor: 28,
  },
  {
    id: 'm16',
    messierId: 'M16',
    nameEn: 'Eagle Nebula',
    nameZh: '鹰状星云',
    type: 'emission',
    raH: 18,
    raM: 18.8,
    decDeg: -13.78,
    distanceLy: 7000,
    apparentMagnitude: 6.4,
    sizeArcMinMajor: 35,
    sizeArcMinMinor: 28,
  },
  {
    id: 'm17',
    messierId: 'M17',
    nameEn: 'Omega Nebula',
    nameZh: '欧米茄星云',
    type: 'emission',
    raH: 18,
    raM: 20.8,
    decDeg: -16.18,
    distanceLy: 5000,
    apparentMagnitude: 6.0,
    sizeArcMinMajor: 46,
    sizeArcMinMinor: 37,
  },
  {
    id: 'ngc-7000',
    ngcId: '7000',
    nameEn: 'North America Nebula',
    nameZh: '北美洲星云',
    type: 'emission',
    raH: 20,
    raM: 59.3,
    decDeg: 44.53,
    distanceLy: 1800,
    apparentMagnitude: 7.5,
    sizeArcMinMajor: 120,
    sizeArcMinMinor: 100,
  },
  {
    id: 'ngc-2237',
    ngcId: '2237',
    nameEn: 'Rosette Nebula',
    nameZh: '玫瑰星云',
    type: 'emission',
    raH: 6,
    raM: 32.3,
    decDeg: 5.03,
    distanceLy: 5000,
    apparentMagnitude: 8.5,
    sizeArcMinMajor: 80,
    sizeArcMinMinor: 60,
  },
  // 行星状星云
  {
    id: 'm27',
    messierId: 'M27',
    nameEn: 'Dumbbell Nebula',
    nameZh: '哑铃星云',
    type: 'planetary',
    raH: 19,
    raM: 59.6,
    decDeg: 22.72,
    distanceLy: 1360,
    apparentMagnitude: 7.5,
    sizeArcMinMajor: 8,
    sizeArcMinMinor: 5.8,
  },
  {
    id: 'm57',
    messierId: 'M57',
    nameEn: 'Ring Nebula',
    nameZh: '环状星云',
    type: 'planetary',
    raH: 18,
    raM: 53.6,
    decDeg: 33.03,
    distanceLy: 2300,
    apparentMagnitude: 8.8,
    sizeArcMinMajor: 1.4,
    sizeArcMinMinor: 1,
  },
  {
    id: 'm97',
    messierId: 'M97',
    nameEn: 'Owl Nebula',
    nameZh: '猫头鹰星云',
    type: 'planetary',
    raH: 11,
    raM: 14.8,
    decDeg: 55.02,
    distanceLy: 2600,
    apparentMagnitude: 9.9,
    sizeArcMinMajor: 3.4,
    sizeArcMinMinor: 3.3,
  },
  // 超新星遗迹
  {
    id: 'm1',
    messierId: 'M1',
    nameEn: 'Crab Nebula',
    nameZh: '蟹状星云',
    type: 'snr',
    raH: 5,
    raM: 34.5,
    decDeg: 22.02,
    distanceLy: 6500,
    apparentMagnitude: 8.4,
    sizeArcMinMajor: 6,
    sizeArcMinMinor: 4,
  },
  {
    id: 'ngc-6960',
    ngcId: '6960',
    nameEn: 'Veil Nebula',
    nameZh: '面纱星云',
    type: 'snr',
    raH: 20,
    raM: 45.7,
    decDeg: 30.72,
    distanceLy: 2400,
    apparentMagnitude: 7.0,
    sizeArcMinMajor: 120,
    sizeArcMinMinor: 120,
  },
  // 反射星云
  {
    id: 'm78',
    messierId: 'M78',
    nameEn: 'M78',
    nameZh: 'M78 反射星云',
    type: 'reflection',
    raH: 5,
    raM: 46.7,
    decDeg: 0.05,
    distanceLy: 1600,
    apparentMagnitude: 8.3,
    sizeArcMinMajor: 8,
    sizeArcMinMinor: 6,
  },
  // 星系
  {
    id: 'm31',
    messierId: 'M31',
    nameEn: 'Andromeda Galaxy',
    nameZh: '仙女座星系',
    type: 'galaxy',
    raH: 0,
    raM: 42.7,
    decDeg: 41.27,
    distanceLy: 2537000,
    apparentMagnitude: 3.4,
    sizeArcMinMajor: 190,
    sizeArcMinMinor: 60,
  },
  {
    id: 'm33',
    messierId: 'M33',
    nameEn: 'Triangulum Galaxy',
    nameZh: '三角座星系',
    type: 'galaxy',
    raH: 1,
    raM: 33.9,
    decDeg: 30.66,
    distanceLy: 2700000,
    apparentMagnitude: 5.7,
    sizeArcMinMajor: 71,
    sizeArcMinMinor: 42,
  },
  {
    id: 'm51',
    messierId: 'M51',
    nameEn: 'Whirlpool Galaxy',
    nameZh: '涡状星系',
    type: 'galaxy',
    raH: 13,
    raM: 29.9,
    decDeg: 47.2,
    distanceLy: 23000000,
    apparentMagnitude: 8.4,
    sizeArcMinMajor: 11.2,
    sizeArcMinMinor: 6.9,
  },
  {
    id: 'm81',
    messierId: 'M81',
    nameEn: "Bode's Galaxy",
    nameZh: '波德星系',
    type: 'galaxy',
    raH: 9,
    raM: 55.6,
    decDeg: 69.07,
    distanceLy: 11800000,
    apparentMagnitude: 6.9,
    sizeArcMinMajor: 27,
    sizeArcMinMinor: 14,
  },
  {
    id: 'm82',
    messierId: 'M82',
    nameEn: 'Cigar Galaxy',
    nameZh: '雪茄星系',
    type: 'galaxy',
    raH: 9,
    raM: 55.8,
    decDeg: 69.68,
    distanceLy: 11400000,
    apparentMagnitude: 8.4,
    sizeArcMinMajor: 11.2,
    sizeArcMinMinor: 4.3,
  },
  {
    id: 'm104',
    messierId: 'M104',
    nameEn: 'Sombrero Galaxy',
    nameZh: '草帽星系',
    type: 'galaxy',
    raH: 12,
    raM: 40,
    decDeg: -11.62,
    distanceLy: 29000000,
    apparentMagnitude: 8.0,
    sizeArcMinMajor: 8.7,
    sizeArcMinMinor: 3.5,
  },
  {
    id: 'm87',
    messierId: 'M87',
    nameEn: 'Virgo A',
    nameZh: '室女座A星系',
    type: 'galaxy',
    raH: 12,
    raM: 30.8,
    decDeg: 12.39,
    distanceLy: 53000000,
    apparentMagnitude: 8.6,
    sizeArcMinMajor: 8.3,
    sizeArcMinMinor: 6.6,
  },
  {
    id: 'm101',
    messierId: 'M101',
    nameEn: 'Pinwheel Galaxy',
    nameZh: '风车星系',
    type: 'galaxy',
    raH: 14,
    raM: 3.2,
    decDeg: 54.35,
    distanceLy: 21000000,
    apparentMagnitude: 7.9,
    sizeArcMinMajor: 29,
    sizeArcMinMinor: 27,
  },
];

function arcMinToRad(arcMin: number): number {
  return (arcMin / 60) * (Math.PI / 180);
}

function buildNebulae(): Nebula[] {
  const seen = new Set<string>();
  return SEEDS.map((s) => {
    if (seen.has(s.id)) throw new Error(`重复星云 id: ${s.id}`);
    seen.add(s.id);
    const raDeg = (s.raH + s.raM / 60) * 15;
    const celestial = equatorialToGalacticCartesian(raDeg, s.decDeg, s.distanceLy);
    const angularRadiusRad = arcMinToRad(s.sizeArcMinMajor / 2);
    return {
      id: s.id,
      messierId: s.messierId,
      ngcId: s.ngcId,
      nameEn: s.nameEn,
      nameZh: s.nameZh,
      type: s.type,
      coords: { galactic: celestial.galactic, cartesian: celestial.cartesian },
      apparentMagnitude: s.apparentMagnitude,
      sizeArcMin: { major: s.sizeArcMinMajor, minor: s.sizeArcMinMinor },
      distanceLy: s.distanceLy,
      visualRadiusLy: angularRadiusRad * s.distanceLy,
    };
  });
}

function main(): void {
  const nebulae = buildNebulae();
  for (const n of nebulae) {
    const c = n.coords.cartesian;
    if (!Number.isFinite(c.xLy) || !Number.isFinite(c.yLy) || !Number.isFinite(c.zLy)) {
      throw new Error(`星云 ${n.id} 坐标含 NaN`);
    }
  }
  mkdirSync(resolve(OUT_FILE, '..'), { recursive: true });
  writeFileSync(
    resolve(OUT_FILE),
    JSON.stringify({ sourceVersion: 'nebulae-v1', count: nebulae.length, nebulae }, null, 2),
  );
  console.log(`已生成 ${OUT_FILE}: ${nebulae.length} 个星云/星团（sourceVersion=nebulae-v1）`);
}

main();
